[package]
name = "qdb"
version = "0.1.10"
edition = "2021"
description = "Library for interacting with QDB"
license = "MIT OR Apache-2.0"

[lib]
name = "qdb"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.38"
serde_json = "1.0.128"
